name: gestion_inventario_prestamos_patrick
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ğŸ“· QR scanner
  mobile_scanner: ^3.5.7

  # ğŸŒ HTTP compatible con Dart 3.2.6
  http: 1.2.0

  # ğŸ“… intl compatible
  intl: 0.19.0

  # ğŸ”¥ Firebase compatibles con Flutter 3.16.x
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Compatibles con Dart 3.2.6
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

