name: Flutter CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  inicio:
    runs-on: ubuntu-latest
    steps:
      - name: Inicio del pipeline
        run: echo "Iniciando CI/CD para app Flutter"

  build:
    runs-on: ubuntu-latest
    needs: inicio

    steps:
      - name: Checkout c√≥digo
        uses: actions/checkout@v3

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.16.9"

      - name: Obtener dependencias
        run: flutter pub get

      - name: Ejecutar tests (sin detener pipeline si fallan)
        run: flutter test integration_test || true

      - name: Build APK sin validar Gradle/AGP
        run: flutter build apk --release --android-skip-build-dependency-validation

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  despliegue:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Despliegue finalizado
        run: echo "APK generado correctamente y listo para descargar."
