name: Flutter CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  inicio:
    runs-on: ubuntu-latest
    steps:
      - name: Inicio del pipeline
        run: echo "Iniciando CI/CD para app Flutter"

  build:
    runs-on: ubuntu-latest
    needs: inicio

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'   # ✔ Versión válida

      - name: Obtener dependencias
        run: flutter pub get

      - name: Ejecutar tests
        run: flutter test integration_test || true

      - name: Build APK
        run: flutter build apk --release

      - name: Guardar APK
        uses: actions/upload-artifact@v4   # ✔ Versión correcta
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  despliegue:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Despliegue completado
        run: echo "APK generado y disponible para descargar."
